language: R
sudo: required
warnings_are_errors: true

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y -q --no-install-recommends nvidia-cuda-toolkit

r_github_packages:
  - wrathematics/float
